version: "3"
services:
  auer_bot:
    build: .
    env_file: "dev.env"
    networks:
      - timescaledb_multi_app_postgres
    volumes:
        - auer_bot_database:/var/lib/auer_telegram_bot

volumes:
    auer_bot_database:

networks:
  timescaledb_multi_app_postgres:
    external: true