version: "3"
services:
  auer_bot:
    build: .
    env_file: "dev.env"
    networks:
      - postgres 
  db:
    container_name: timescaledb 
    image: timescale/timescaledb:latest-pg12 
    restart: always
    volumes:
      - "db_data:/var/lib/postgresql/data/"

    networks:
      - postgres
    env_file:
      - ".env"
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:6.2
    restart: always
    volumes:
      - "pgadmin:/var/lib/pgadmin/"
    ports:
      - "5050:80"
    networks:
      - postgres
    env_file:
      - ".env"

networks:
  postgres:

volumes:
  db_data:
  pgadmin:
