version: "3"
services:
  auer_bot:
    build: .
    env_file: "dev.env"
    environment: 
        - SQLITE_PATH=/var/lib/auer_telegram_bot/client_db.sqlite
    volumes:
        - auer_bot_database:/var/lib/auer_telegram_bot

volumes:
    auer_bot_database: