---
version: 1
disable_existing_loggers: False
formatters:
  default:
    format: "[%(asctime)s] [%(process)s] [%(name)s] [%(levelname)s] %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout

root:
  level: INFO 
  handlers: [console]

loggers:
  auer_b_telegram_bot:
    level: DEBUG
    handlers: [console]
    propagate: no
